version: "3"

services:
  react-native-test-ci:
    container_name: react-native-test-ci
    privileged: true
    command: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]
    environment:
      - DISPLAY
      - ANDROID_AVD_HOME=/img
      - NODE_ENV=production
    build: 
      context: .
      dockerfile: Dockerfile
    image: react-native-test-ci
    ports:
      - 8081:8081
      - 19001:19001
      - 19000:19000
      - 5037:5037
    volumes: 
      - ./bash:/usr/local/bin/
      - ./src:/project
      - ./build/img:/img
    network_mode: "host"
